[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
via_ir = true
fs_permissions = [{access = "read", path = "./images/"}]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
