[profile.solx]
solc_version = "/Users/haz/.local/bin/solx"
optimization = 3
gas_limit = 100_000_000
fs_permissions = [{access = "read", path = "./images/"}, { access = "write", path = "./output/"}]
#fuzz_runs = 1000
#invariant_runs = 500
#invariant_depth = 20

[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
via_ir = true
optimizer = true
#optimizer-runs = 2000
optimizer-runs = 1000000
fs_permissions = [
    {access = "read", path = "./images/"}, 
    { access = "write", path = "./output/"}, 
    {access = "read", path = "./broadcast"},
    { access = "read", path = "./reports" },
]
gas_reports = ["*"]
fuzz_runs = 1000
invariant_runs = 500
invariant_depth = 20
env = { PRIVATE_KEY = "${PRIVATE_KEY}" }

[dependencies]
openzeppelin-contracts = "https://github.com/OpenZeppelin/openzeppelin-contracts#next-v5.0"

[profile.default.rpc_endpoints]
sepolia-eth = "${SEPOLIA_RPC_URL}"
arb-sepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"
base-sepolia = "${BASE_SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=11155111" }
arbitrum-sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=421614", chain = "421614" }
optimism-sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=11155420", chain = "11155420" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options



